# Generated by Django 4.2.1 on 2023-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descartadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descartadores',
            name='email',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
